-d C:\gowin_prj\shift_registr\impl\gwsynthesis\shift_registr.vg
-p GW2AR-18C-QFN88P-8
-pn GW2AR-LV18QN88PC8/I7
-cst C:\gowin_prj\shift_registr\src\shift_registr.cst
-cfg C:\gowin_prj\shift_registr\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
